# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
